name: face2bmi
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.11
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  # --- Core Data Libraries ---
  - numpy=1.24.3
  - pandas=1.5.3
  - scipy=1.15.3
  - scikit-learn=1.7.2
  - pip
  - pip:
      - xgboost==3.2.0
      - opencv-python==4.9.0.80
      - pillow==9.4.0
      - streamlit==1.63.0
      - plotly==7.0.0
      - fpdf2==2.8.8
      - joblib==1.5.3
      - pyreadstat>=1.2.0
      - pyarrow==14.0.2